const activityTypes: { [name: string]: string } = {
  'Hike,Run,Walk': 'All on foot',
  AlpineSki: 'Downhill skiing',
  BackcountrySki: 'Off-piste skiing',
  Canoeing: 'Canoeing',
  Crossfit: 'Crossfit',
  EBikeRide: 'E-bike',
  Elliptical: 'Cross-trainer',
  Golf: 'Golf',
  Handcycle: 'Handcycling',
  Hike: 'Hiking',
  IceSkate: 'Ice skating',
  InlineSkate: 'Inline skating',
  Kayaking: 'Kayaking',
  Kitesurf: 'Kitesurfing',
  NordicSki: 'Cross-country skiing',
  Ride: 'Cycling',
  RockClimbing: 'Rock climbing',
  RollerSki: 'Roller skiing',
  Rowing: 'Rowing',
  Run: 'Running',
  Sail: 'Sailing',
  Skateboard: 'Skateboarding',
  Snowboard: 'Snowboarding',
  Snowshoe: 'Snowshoing',
  Soccer: 'Football',
  StairStepper: 'Stair stepper',
  StandUpPaddling: 'Stand up paddleboarding',
  Surfing: 'Surfing',
  Swim: 'Swimming',
  Velomobile: 'Velomobile',
  VirtualRide: 'Virtual cycling',
  VirtualRun: 'Virtual running',
  Walk: 'Walking',
  WeightTraining: 'Weight training',
  Wheelchair: 'Wheelchair',
  Windsurf: 'Windsurfing',
  Workout: 'Workout',
  Yoga: 'Yoga',
};
export default activityTypes;
