#!/usr/bin/env bash

cd "$(dirname "$0")/.." &&

. scripts/connect &&

(
  DEPLOY_COMMAND="$(printf "docker-compose -f%q/docker-compose.yml up --build -d && docker system prune -f" "${DEPLOY_DIR:-.}")"

  rsync -re"ssh $DEPLOY_FLAG" dist/ "$DEPLOY_TARGET":"${DEPLOY_DIR:-.}" &&
  ssh "$DEPLOY_FLAG" "$DEPLOY_TARGET" "$DEPLOY_COMMAND"
)
